// Semantic tag vocabulary for translatable strings.
// Translators preserve these tags verbatim; real HTML (URLs, classes,
// attributes) lives here so it stays out of the locale files.
var I18N_TAGS = {
  "note":          ['<strong class="important">', "</strong>"],
  "emph":          ["<strong>", "</strong>"],
  "official-site": ['<a href="http://git.io/2048">', "</a>"],
  "author":        ['<a href="http://gabrielecirulli.com" target="_blank">', "</a>"],
  "source":        ['<a href="https://itunes.apple.com/us/app/1024!/id823499224" target="_blank">', "</a>"],
  "inspiration":   ['<a href="http://asherv.com/threes/" target="_blank">', "</a>"],
  "weblate":       ['<a href="https://hosted.weblate.org/projects/2048/2048/">', "</a>"]
};

function expandI18nTags(str) {
  for (var tag in I18N_TAGS) {
    if (!I18N_TAGS.hasOwnProperty(tag)) continue;
    var esc = tag.replace(/[-/\\^$*+?.()|[\]{}]/g, "\\$&");
    str = str.replace(new RegExp("<" + esc + ">", "g"), I18N_TAGS[tag][0]);
    str = str.replace(new RegExp("</" + esc + ">", "g"), I18N_TAGS[tag][1]);
  }
  return str;
}

function normalizeLocaleTag(tag) {
  // "pt-BR" -> "pt_BR", "sco-ulster" -> "sco_ulster". File names use
  // underscore instead of hyphen but are otherwise valid BCP 47 tags.
  return (tag || "").replace(/-/g, "_");
}

function I18n() {
  this.locale = this.detectLocale();
  this.translations = {};
  this.supported = [];
  this.ready = false;
}

I18n.prototype.detectLocale = function () {
  // URL parameter takes priority
  var match = window.location.search.match(/[?&]lang=([a-zA-Z_\-]+)/);
  if (match) return normalizeLocaleTag(match[1]);

  // Then localStorage
  try {
    var stored = window.localStorage.getItem("2048-locale");
    if (stored) return stored;
  } catch (e) {}

  // Then browser language; load() will cascade-fallback if unsupported
  return normalizeLocaleTag(navigator.language || navigator.userLanguage || "en");
};

// What locale the user would get without any URL param or stored preference.
// Requires the manifest (this.supported) to be populated. Used by updateUrl
// to decide whether to include ?lang= in the URL.
I18n.prototype.defaultLocale = function () {
  var nav = normalizeLocaleTag(navigator.language || navigator.userLanguage || "en");
  var list = this.supported || [];
  for (var i = 0; i < list.length; i++) {
    if (list[i].code === nav) return nav;
  }
  var base = nav.split("_")[0].toLowerCase();
  for (var j = 0; j < list.length; j++) {
    if (list[j].code === base) return base;
  }
  return "en";
};

// Load the list of supported locales from locales/index.json (generated by
// scripts/build_locales_manifest.py at build time). If unavailable, the
// switcher will be hidden.
I18n.prototype.loadManifest = function (callback) {
  var self = this;
  var xhr = new XMLHttpRequest();
  xhr.open("GET", "locales/index.json", true);
  var done = function (list) {
    self.supported = list || [];
    if (callback) callback(self.supported);
  };
  xhr.onload = function () {
    if (xhr.status === 200) {
      try {
        done(JSON.parse(xhr.responseText));
      } catch (e) {
        console.warn("I18n: failed to parse locales/index.json");
        done([]);
      }
    } else {
      done([]);
    }
  };
  xhr.onerror = function () { done([]); };
  xhr.send();
};

I18n.prototype.load = function (callback) {
  var self = this;

  var done = function () {
    self.ready = true;
    self.apply();
    if (callback) callback();
  };

  var xhr = new XMLHttpRequest();
  xhr.open("GET", "locales/" + this.locale + ".json", true);
  xhr.onload = function () {
    if (xhr.status === 200) {
      try {
        self.translations = JSON.parse(xhr.responseText);
      } catch (e) {
        console.warn("I18n: failed to parse locale file for '" + self.locale + "'");
      }
      done();
    } else if (self.locale.indexOf("_") !== -1) {
      // Region-qualified file not found, fall back to language-only code
      self.locale = self.locale.split("_")[0];
      self.load(callback);
    } else if (self.locale !== "en") {
      // Locale file not found, fall back to English
      self.locale = "en";
      self.load(callback);
    } else {
      // Even English failed — proceed with HTML defaults
      done();
    }
  };
  xhr.onerror = function () {
    // Network error — proceed with HTML defaults
    done();
  };
  xhr.send();
};

I18n.prototype.t = function (key) {
  var value = this.translations[key];
  return value ? expandI18nTags(value) : key;
};

I18n.prototype.apply = function () {
  var self = this;

  // Translate elements with data-i18n (sets innerHTML)
  var elements = document.querySelectorAll("[data-i18n]");
  for (var i = 0; i < elements.length; i++) {
    var key = elements[i].getAttribute("data-i18n");
    var translation = self.translations[key];
    if (translation) {
      elements[i].innerHTML = expandI18nTags(translation);
    }
  }

  // Translate data-label attributes (for CSS pseudo-element content)
  var labelElements = document.querySelectorAll("[data-i18n-label]");
  for (var j = 0; j < labelElements.length; j++) {
    var labelKey = labelElements[j].getAttribute("data-i18n-label");
    var labelTranslation = self.translations[labelKey];
    if (labelTranslation) {
      labelElements[j].setAttribute("data-label", expandI18nTags(labelTranslation));
    }
  }

  // Update html lang attribute
  document.documentElement.setAttribute("lang", self.locale);
};

I18n.prototype.setLocale = function (locale) {
  this.locale = locale;
  try {
    window.localStorage.setItem("2048-locale", locale);
  } catch (e) {}
  this.translations = {};
  this.ready = false;
  this.load();
};

// Populate a <select> element with supported locales and wire up a change
// handler that switches language and updates the URL. If the manifest is
// empty (e.g. locales/index.json was not generated), the enclosing bar is
// hidden so the UI doesn't show an empty dropdown.
//
// Locales with a "family" field are grouped under a disabled <option> that
// acts as a non-selectable heading, so dialect variants (e.g. sco_ulster)
// appear indented beneath a parent label (Scots). The group heading appears
// at the position of its first visible member in the manifest order; if a
// family has no visible members, its heading is not emitted at all.
//
// Locales with "hidden": true in the manifest are skipped here (but remain
// loadable via ?lang=<code> for testing). We use disabled options instead of
// <optgroup> because Firefox (and some other engines) render optgroup labels
// with native widget styling that ignores CSS font-weight/font-style/color.
// Disabled options, by contrast, pick up the browser's native "inactive"
// styling consistently.
var I18N_GROUP_INDENT = "\u00a0\u00a0\u00a0\u00a0"; // four nbsps
I18n.prototype.mountSwitcher = function (element) {
  if (!element) return;
  var list = this.supported || [];
  if (list.length === 0) {
    var bar = element.parentNode;
    if (bar) bar.style.display = "none";
    return;
  }
  var self = this;
  element.innerHTML = "";

  var seenFamilies = {};

  for (var i = 0; i < list.length; i++) {
    var entry = list[i];
    if (entry.hidden) continue;

    if (entry.family && !seenFamilies[entry.family]) {
      seenFamilies[entry.family] = true;
      var header = document.createElement("option");
      header.disabled = true;
      header.textContent = entry.family;
      header.className = "language-group-heading";
      element.appendChild(header);
    }

    var opt = document.createElement("option");
    opt.value = entry.code;
    opt.textContent = entry.family ? I18N_GROUP_INDENT + entry.name : entry.name;
    if (entry.code === this.locale) opt.selected = true;
    element.appendChild(opt);
  }

  element.addEventListener("change", function () {
    self.setLocale(element.value);
    self.updateUrl();
  });
};

// Keep the URL in sync with the current locale so links are shareable.
// Strips ?lang= when the user is viewing their browser default; otherwise
// sets ?lang=<current>.
I18n.prototype.updateUrl = function () {
  if (!window.history || !window.history.replaceState) return;

  var search = window.location.search || "";
  // Remove any existing lang param.
  search = search.replace(/([?&])lang=[^&]*(&|$)/, function (_, pre, post) {
    return post ? pre : "";
  });
  if (search === "?") search = "";

  if (this.locale !== this.defaultLocale()) {
    search += (search ? "&" : "?") + "lang=" + encodeURIComponent(this.locale);
  }

  var newUrl = window.location.pathname + search + window.location.hash;
  var currentUrl = window.location.pathname + (window.location.search || "") + (window.location.hash || "");
  if (newUrl !== currentUrl) {
    window.history.replaceState({}, "", newUrl);
  }
};
